In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import neighbors

In [2]:
import matplotlib.pyplot as plt
from matplotlib import style
%matplotlib inline
style.use("fivethirtyeight")

In [5]:
df = pd.read_csv('../../dataset/breast-cancer-wisconsin.data.txt')

In [6]:
df.head()

,id,Clump_Thickness,unif_cell_s,unif_cell_shape,Marginal_Adhesion,Single_Epithelial_cell_s,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
id                          699 non-null int64
Clump_Thickness             699 non-null int64
unif_cell_s                 699 non-null int64
unif_cell_shape             699 non-null int64
Marginal_Adhesion           699 non-null int64
Single_Epithelial_cell_s    699 non-null int64
Bare_Nuclei                 699 non-null object
Bland_Chromatin             699 non-null int64
Normal_Nucleoli             699 non-null int64
Mitoses                     699 non-null int64
class                       699 non-null int64
dtypes: int64(10), object(1)
memory usage: 60.1+ KB

In [8]:
df.describe()

,id,Clump_Thickness,unif_cell_s,unif_cell_shape,Marginal_Adhesion,Single_Epithelial_cell_s,Bland_Chromatin,Normal_Nucleoli,Mitoses,class
count,6.990000e+02,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000
mean,1.071704e+06,4.417740,3.134478,3.207439,2.806867,3.216023,3.437768,2.866953,1.589413,2.689557
std,6.170957e+05,2.815741,3.051459,2.971913,2.855379,2.214300,2.438364,3.053634,1.715078,0.951273
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,8.706885e+05,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000
50%,1.171710e+06,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,2.000000
75%,1.238298e+06,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,1.000000,4.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000

In [33]:
df.drop(['id'],1,inplace = True)
df.replace('?',-99999,inplace = True)

# preper data
X = np.array(df.drop(['class'],1))
y = np.array(df['class'])

# split data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

# preper model
clf = neighbors.KNeighborsClassifier()

# fitting model
clf = clf.fit(X_train , y_train)

# show the accuracy
accuracy = clf.score(X_test, y_test)
print(accuracy)

# example 
example = np.array([[1,4,1,1,6,3,0,5,4]])
example = example.reshape(len(example) , -1)

# perdict
predict_example = clf.predict(example)
print(predict_example)

0.9714285714285714
[2]